# Generated by Django 5.1.6 on 2025-02-16 22:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djpost',
            name='uniqueId',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AlterModelTable(
            name='djpost',
            table='posts_DJPost',
        ),
    ]
